version: '3'
services:
  discovery:
    image: tbinay/netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
  spring-cloud-config-server:
    image: tbinay/spring-cloud-config-server:0.0.1-SNAPSHOT
    ports:
      - 8888:8888
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
  hrms:
    image: tbinay/employee-management-system:0.0.1-SNAPSHOT
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail -s http://discovery:8761/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - spring-cloud-config-server
