spring:
  application:
    name: spring-cloud-config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BinayTripathi/EBS-Cloud-Config-Repo.git
    
server:
  port: 8888
  
  
eureka:
  instance:
    instance-id: spring-cloud-config-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}